
vimtest: executable
	./executable

executable: source.o cfacil.o
	g++ `pkg-config --libs sdl` `pkg-config --libs gl` -o executable -lm -Wl,--wrap,main cfacil.o source.o 

source.o: source.cpp
	g++ -Wall `pkg-config --cflags sdl` `pkg-config --cflags gl` -c source.cpp

cfacil.o: cfacil.h cfacil.cpp
	g++ -Wall `pkg-config --cflags sdl` `pkg-config --cflags gl` -c cfacil.cpp

clean:
	rm -f cfacil.o  source.o
	rm -f ./executable

